# Generated by Django 3.2 on 2023-10-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='subjects',
            field=models.ManyToManyField(to='api.Subject'),
        ),
    ]
