# Generated by Django 3.2 on 2023-10-19 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_group_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
