# Generated by Django 3.2 on 2023-10-19 06:08

import api.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='day',
            field=api.models.DayOfTheWeekField(choices=[('friday', 'Friday'), ('monday', 'Monday'), ('saturday', 'Saturday'), ('sunday', 'Sunday'), ('thursday', 'Thursday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday')], default='monday', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
