# Generated by Django 3.2 on 2023-10-19 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20231019_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='subject',
        ),
    ]
